alter table public.zumra_member_profiles
  add column if not exists display_name text;

create table if not exists public.zumra_groups (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  sector text not null,
  objective text not null,
  participation_mode text not null
    check (participation_mode in ('physical', 'digital', 'both')),
  country text,
  city text,
  status text not null default 'forming'
    check (status in ('forming', 'active', 'suspended', 'closed')),
  founder_core_identity_reference text not null
    references public.zumra_memberships(core_identity_reference),
  core_organisation_reference text,
  activated_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (
    participation_mode = 'digital'
    or (nullif(btrim(country), '') is not null and nullif(btrim(city), '') is not null)
  )
);

create table if not exists public.zumra_group_members (
  id uuid primary key default gen_random_uuid(),
  zumra_id uuid not null references public.zumra_groups(id) on delete cascade,
  core_identity_reference text not null
    references public.zumra_memberships(core_identity_reference),
  status text not null default 'active'
    check (status in ('active', 'left', 'removed')),
  joined_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (zumra_id, core_identity_reference)
);

create table if not exists public.zumra_group_roles (
  id uuid primary key default gen_random_uuid(),
  zumra_id uuid not null references public.zumra_groups(id) on delete cascade,
  core_identity_reference text not null,
  role text not null
    check (role in ('principal', 'deputy_1', 'deputy_2', 'finance', 'social')),
  assigned_by text not null,
  assigned_at timestamptz not null default now(),
  unique (zumra_id, role),
  unique (zumra_id, core_identity_reference),
  foreign key (zumra_id, core_identity_reference)
    references public.zumra_group_members(zumra_id, core_identity_reference)
    on delete cascade
);

create table if not exists public.zumra_group_invites (
  id uuid primary key default gen_random_uuid(),
  zumra_id uuid not null references public.zumra_groups(id) on delete cascade,
  token_hash text not null unique,
  status text not null default 'open'
    check (status in ('open', 'used', 'revoked')),
  created_by text not null,
  used_by text,
  expires_at timestamptz not null,
  used_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.zumra_group_events (
  id bigint generated by default as identity primary key,
  zumra_id uuid not null references public.zumra_groups(id) on delete cascade,
  event_type text not null,
  actor_core_identity_reference text not null,
  subject_core_identity_reference text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists zumra_groups_status_idx
  on public.zumra_groups(status);
create index if not exists zumra_group_members_identity_idx
  on public.zumra_group_members(core_identity_reference, status);
create index if not exists zumra_group_invites_status_expiry_idx
  on public.zumra_group_invites(status, expires_at);
create index if not exists zumra_group_events_zumra_created_idx
  on public.zumra_group_events(zumra_id, created_at desc);

alter table public.zumra_groups enable row level security;
alter table public.zumra_group_members enable row level security;
alter table public.zumra_group_roles enable row level security;
alter table public.zumra_group_invites enable row level security;
alter table public.zumra_group_events enable row level security;

drop trigger if exists zumra_groups_touch_updated_at on public.zumra_groups;
create trigger zumra_groups_touch_updated_at
before update on public.zumra_groups
for each row execute function public.zumra_touch_updated_at();

drop trigger if exists zumra_group_members_touch_updated_at on public.zumra_group_members;
create trigger zumra_group_members_touch_updated_at
before update on public.zumra_group_members
for each row execute function public.zumra_touch_updated_at();

create or replace function public.zumra_recompute_group_status(p_zumra_id uuid)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_current text;
  v_next text;
  v_members integer;
  v_roles integer;
begin
  select status into v_current
  from public.zumra_groups
  where id = p_zumra_id
  for update;

  if v_current is null then
    raise exception 'ZUMRA_INTROUVABLE';
  end if;

  if v_current in ('suspended', 'closed') then
    return v_current;
  end if;

  select count(*) into v_members
  from public.zumra_group_members
  where zumra_id = p_zumra_id and status = 'active';

  select count(distinct role) into v_roles
  from public.zumra_group_roles
  where zumra_id = p_zumra_id;

  v_next := case when v_members >= 5 and v_roles = 5 then 'active' else 'forming' end;

  if v_next <> v_current then
    update public.zumra_groups
    set status = v_next,
        activated_at = case
          when v_next = 'active' then coalesce(activated_at, now())
          else activated_at
        end
    where id = p_zumra_id;

    insert into public.zumra_group_events (
      zumra_id,
      event_type,
      actor_core_identity_reference,
      payload
    )
    select
      p_zumra_id,
      case when v_next = 'active' then 'group_activated' else 'group_returned_to_formation' end,
      founder_core_identity_reference,
      jsonb_build_object('members', v_members, 'roles', v_roles)
    from public.zumra_groups
    where id = p_zumra_id;
  end if;

  return v_next;
end;
$$;

create or replace function public.zumra_create_group(
  p_actor text,
  p_name text,
  p_sector text,
  p_objective text,
  p_participation_mode text,
  p_country text,
  p_city text
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id uuid;
  v_membership_status text;
begin
  select status into v_membership_status
  from public.zumra_memberships
  where core_identity_reference = p_actor;

  if v_membership_status is distinct from 'active' then
    raise exception 'ADHESION_ZUMRA_NON_ACTIVE';
  end if;

  if p_participation_mode not in ('physical', 'digital', 'both') then
    raise exception 'MODE_PARTICIPATION_INVALIDE';
  end if;

  if p_participation_mode <> 'digital'
     and (nullif(btrim(p_country), '') is null or nullif(btrim(p_city), '') is null) then
    raise exception 'LOCALISATION_REQUISE';
  end if;

  insert into public.zumra_groups (
    name,
    sector,
    objective,
    participation_mode,
    country,
    city,
    founder_core_identity_reference
  ) values (
    btrim(p_name),
    btrim(p_sector),
    btrim(p_objective),
    p_participation_mode,
    nullif(btrim(p_country), ''),
    nullif(btrim(p_city), ''),
    p_actor
  ) returning id into v_id;

  insert into public.zumra_group_members (
    zumra_id,
    core_identity_reference,
    status
  ) values (v_id, p_actor, 'active');

  insert into public.zumra_group_roles (
    zumra_id,
    core_identity_reference,
    role,
    assigned_by
  ) values (v_id, p_actor, 'principal', p_actor);

  insert into public.zumra_group_events (
    zumra_id,
    event_type,
    actor_core_identity_reference,
    subject_core_identity_reference
  ) values (v_id, 'group_created', p_actor, p_actor);

  return v_id;
end;
$$;

create or replace function public.zumra_create_invite(
  p_zumra_id uuid,
  p_actor text,
  p_token_hash text,
  p_expires_at timestamptz
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id uuid;
begin
  if not exists (
    select 1
    from public.zumra_group_roles r
    join public.zumra_group_members m
      on m.zumra_id = r.zumra_id
     and m.core_identity_reference = r.core_identity_reference
    where r.zumra_id = p_zumra_id
      and r.role = 'principal'
      and r.core_identity_reference = p_actor
      and m.status = 'active'
  ) then
    raise exception 'RESPONSABLE_PRINCIPAL_REQUIS';
  end if;

  if p_expires_at <= now() then
    raise exception 'EXPIRATION_INVALIDE';
  end if;

  insert into public.zumra_group_invites (
    zumra_id,
    token_hash,
    created_by,
    expires_at
  ) values (p_zumra_id, p_token_hash, p_actor, p_expires_at)
  returning id into v_id;

  insert into public.zumra_group_events (
    zumra_id,
    event_type,
    actor_core_identity_reference,
    payload
  ) values (
    p_zumra_id,
    'invite_created',
    p_actor,
    jsonb_build_object('invite_id', v_id, 'expires_at', p_expires_at)
  );

  return v_id;
end;
$$;

create or replace function public.zumra_accept_invite(
  p_token_hash text,
  p_actor text
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_invite public.zumra_group_invites%rowtype;
  v_membership_status text;
begin
  select status into v_membership_status
  from public.zumra_memberships
  where core_identity_reference = p_actor;

  if v_membership_status is distinct from 'active' then
    raise exception 'ADHESION_ZUMRA_NON_ACTIVE';
  end if;

  select * into v_invite
  from public.zumra_group_invites
  where token_hash = p_token_hash
    and status = 'open'
  for update;

  if v_invite.id is null then
    raise exception 'INVITATION_INVALIDE';
  end if;

  if v_invite.expires_at <= now() then
    update public.zumra_group_invites
    set status = 'revoked'
    where id = v_invite.id;
    raise exception 'INVITATION_EXPIREE';
  end if;

  insert into public.zumra_group_members (
    zumra_id,
    core_identity_reference,
    status,
    joined_at
  ) values (
    v_invite.zumra_id,
    p_actor,
    'active',
    now()
  )
  on conflict (zumra_id, core_identity_reference)
  do update set
    status = 'active',
    joined_at = case
      when public.zumra_group_members.status = 'active'
        then public.zumra_group_members.joined_at
      else now()
    end;

  update public.zumra_group_invites
  set status = 'used',
      used_by = p_actor,
      used_at = now()
  where id = v_invite.id;

  insert into public.zumra_group_events (
    zumra_id,
    event_type,
    actor_core_identity_reference,
    subject_core_identity_reference,
    payload
  ) values (
    v_invite.zumra_id,
    'member_joined',
    p_actor,
    p_actor,
    jsonb_build_object('invite_id', v_invite.id)
  );

  perform public.zumra_recompute_group_status(v_invite.zumra_id);
  return v_invite.zumra_id;
end;
$$;

create or replace function public.zumra_assign_founding_role(
  p_zumra_id uuid,
  p_actor text,
  p_target text,
  p_role text
)
returns text
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_role not in ('deputy_1', 'deputy_2', 'finance', 'social') then
    raise exception 'ROLE_INVALIDE';
  end if;

  if not exists (
    select 1 from public.zumra_group_roles
    where zumra_id = p_zumra_id
      and role = 'principal'
      and core_identity_reference = p_actor
  ) then
    raise exception 'RESPONSABLE_PRINCIPAL_REQUIS';
  end if;

  if not exists (
    select 1 from public.zumra_group_members
    where zumra_id = p_zumra_id
      and core_identity_reference = p_target
      and status = 'active'
  ) then
    raise exception 'MEMBRE_INACTIF';
  end if;

  if exists (
    select 1 from public.zumra_group_roles
    where zumra_id = p_zumra_id
      and core_identity_reference = p_target
      and role <> p_role
  ) then
    raise exception 'MEMBRE_DEJA_ROLE_FONDATEUR';
  end if;

  delete from public.zumra_group_roles
  where zumra_id = p_zumra_id and role = p_role;

  insert into public.zumra_group_roles (
    zumra_id,
    core_identity_reference,
    role,
    assigned_by
  ) values (p_zumra_id, p_target, p_role, p_actor);

  insert into public.zumra_group_events (
    zumra_id,
    event_type,
    actor_core_identity_reference,
    subject_core_identity_reference,
    payload
  ) values (
    p_zumra_id,
    'founding_role_assigned',
    p_actor,
    p_target,
    jsonb_build_object('role', p_role)
  );

  return public.zumra_recompute_group_status(p_zumra_id);
end;
$$;

create or replace function public.zumra_transfer_principal(
  p_zumra_id uuid,
  p_actor text,
  p_target text
)
returns text
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_actor = p_target then
    raise exception 'RESPONSABLE_DEJA_EN_PLACE';
  end if;

  if not exists (
    select 1 from public.zumra_group_roles
    where zumra_id = p_zumra_id
      and role = 'principal'
      and core_identity_reference = p_actor
  ) then
    raise exception 'RESPONSABLE_PRINCIPAL_REQUIS';
  end if;

  if not exists (
    select 1 from public.zumra_group_members
    where zumra_id = p_zumra_id
      and core_identity_reference = p_target
      and status = 'active'
  ) then
    raise exception 'MEMBRE_INACTIF';
  end if;

  if exists (
    select 1 from public.zumra_group_roles
    where zumra_id = p_zumra_id
      and core_identity_reference = p_target
  ) then
    raise exception 'MEMBRE_DEJA_ROLE_FONDATEUR';
  end if;

  update public.zumra_group_roles
  set core_identity_reference = p_target,
      assigned_by = p_actor,
      assigned_at = now()
  where zumra_id = p_zumra_id and role = 'principal';

  insert into public.zumra_group_events (
    zumra_id,
    event_type,
    actor_core_identity_reference,
    subject_core_identity_reference,
    payload
  ) values (
    p_zumra_id,
    'principal_transferred',
    p_actor,
    p_target,
    jsonb_build_object('previous_principal', p_actor)
  );

  return public.zumra_recompute_group_status(p_zumra_id);
end;
$$;

revoke all on function public.zumra_recompute_group_status(uuid) from public, anon, authenticated;
revoke all on function public.zumra_create_group(text, text, text, text, text, text, text) from public, anon, authenticated;
revoke all on function public.zumra_create_invite(uuid, text, text, timestamptz) from public, anon, authenticated;
revoke all on function public.zumra_accept_invite(text, text) from public, anon, authenticated;
revoke all on function public.zumra_assign_founding_role(uuid, text, text, text) from public, anon, authenticated;
revoke all on function public.zumra_transfer_principal(uuid, text, text) from public, anon, authenticated;

grant execute on function public.zumra_recompute_group_status(uuid) to service_role;
grant execute on function public.zumra_create_group(text, text, text, text, text, text, text) to service_role;
grant execute on function public.zumra_create_invite(uuid, text, text, timestamptz) to service_role;
grant execute on function public.zumra_accept_invite(text, text) to service_role;
grant execute on function public.zumra_assign_founding_role(uuid, text, text, text) to service_role;
grant execute on function public.zumra_transfer_principal(uuid, text, text) to service_role;

comment on table public.zumra_groups is
  'Groupes de travail ZUMRA. Une Zumra est active a partir de 5 membres actifs et des 5 responsabilites fondatrices attribuees.';
comment on column public.zumra_groups.core_organisation_reference is
  'Reference d organisation GAMAD Core reservee a une integration ulterieure; le groupe en formation reste une donnee metier ZUMRA.';
comment on table public.zumra_group_events is
  'Historique append-only des evenements structurants d une Zumra.';
